# Generated by Django 5.1.1 on 2026-03-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstyle',
            name='voice',
            field=models.CharField(default='alloy', max_length=50),
        ),
    ]
